server:
  port: 8080

spring:
  application:
    name: ssjwt
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wind_dev
    username: root
    password: root
    jpa:
      hibernate:
        ddl-auto: none
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      show-sql: true
      database: mysql
      open-in-view: false
    jackson:
      serialization:
        indent_output: true
  security:
    sign-in-api: /sign/in
    sign-up-api: /sign/up
    logout-api: /logout
    ignore:
      - /ignore
    must:
      - /must

jwt:
  issuer: ssjwt
  prefix: ssjwt-
  # 3天
  expiration: 259200000
  secret: !!str 334568540
  header-key: Authorization
